apiVersion: apps/v1
kind: Deployment
metadata:
  name: as5-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: as5
    spec:
      containers:
      - name: as5
        image: as5:latest
        ports:
        - containerPort: 3001
        env:
        - name: APP_ENV
          value: production
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
