name: Docker Image CI

on:
  push:
    branches: [ "master", "cicd" ]
  pull_request:
    branches: [ "master", "cicd" ]

jobs:

  build:
    runs-on: ubuntu-latest
    - name: upload image to ECR
      uses: appleboy/docker-ecr-action@master
      with:
        access_key: ${{ secrets.aws_access_key_id }}
        secret_key: ${{ secrets.aws_secret_access_key }}
        registry: ${{ secrets.registry }}
        repo: as5
        region: ap-southeast-1
        auto_tag: true
        daemon_off: false
        dockerfile: assignments/assignment_5/backend/Dockerfile
        context: assignments/assignment_5/backend/
