name: Deploy to Amazon ECR

on:
  push:
    branches: [ "master", "cicd" ]
  pull_request:
    branches: [ "master", "cicd" ]

jobs:
  deploy:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0'
      id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: as5
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd assignments/assignment_5/backend/
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push -a $ECR_REGISTRY/$ECR_REPOSITORY

    - name: Update kube config
      run: aws eks update-kubeconfig --name fedhr-cluster --region ap-southeast-1

    # - name: Deploy to EKS
    #   run: |
    #     kubectl apply -f fedhr-postgres-deployment.yaml
    #     kubectl apply -f fedhr-graphene-deployment.yaml
    #     kubectl apply -f fedhr-ingress.yaml

    # - name: Run Tests
    #   run: |
    #     kubectl exec --stdin --tty fedhr-graphene-deployment-5cb9c94d66-8pjgj -- pytest
